version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`    
      - pip install --upgrade awscli
      - echo Executing unit tests...      
      - python -m unittest discover tests
      - echo Compiling the Python code... 
      - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template template-export.yml
artifacts:
  type: zip
  files:
    - template-export.yml
